repos:
-   repo: local
    hooks:
    -   id: run-tests
        name: Run Unit Tests
        entry: python3 -m unittest discover tests
        language: system
        types: [python]
        pass_filenames: false
